config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|fr/ do
    get 'dashboard/data', to: 'dashboard#data', as: :dashboard_data
    get 'dashboard/rapport', to: 'dashboard#rapport', as: :dashboard_rapport
    get "dashboard/download_rapport", to: "dashboard#download_rapport", as: :download_rapport
    get '/help', to: 'pages#help', as: :help
    get '/invited_candidates', to: 'pages#invited_candidates', as: :invited_candidates
    resources :dashboard, only: [:index, :show]
    devise_for :users
    root to: "pages#home"
    get "final_step", to: "pages#final_step", as: :final_step

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end

    resources :audition_applications do
      member do
        patch :update_status
        patch :update_ethnicity
        get :confirm_attendance
        post :confirm_attendance_message
        patch :update_attendance
      end
      collection do
        post :send_results
      end
      resources :votes, only: [:create]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="slideshow">
  <%# <div class="burger" data-slideshow-target="burger">
    <div></div>
    <div></div>
    <div></div>
  </div> %>
  <div class="slideshow" data-slideshow-target="slideshow">
    <div class="slideshow_btn_close">
      <button id="close-toggle-menu" aria-label="Close menu" class="menu-icon" data-slideshow-target="burgerLine">
        <span class="line line1"></span>
      </button>
    </div>

    <svg viewBox="0 0 24 28" fill="none" id="logo-min--sprite" width="30" height="34" xmlns="http://www.w3.org/2000/svg" style="margin-bottom:20px">
      <title>Opéra de Lyon</title>
      <path d="M0 11.7824V16.576H5.5V11.7824C5.54545 8.288 8.40909 5.4656 12 5.4656C15.5909 5.4656 18.4545 8.288 18.5 11.7824V22.3552H14.8182H5.54546V28H24V11.7824C23.9545 5.2864 18.5909 0 12 0C5.36364 0 0 5.2416 0 11.7824Z" fill="currentColor"></path>
      <path d="M0 16.576V11.7824C0 5.2416 5.36364 0 12 0C18.5909 0 23.9545 5.2864 24 11.7824V28H5.54546V22.3552H14.8182H18.5V11.7824C18.4545 8.288 15.5909 5.4656 12 5.4656C8.40909 5.4656 5.54545 8.288 5.5 11.7824V16.576H0Z" fill="currentColor"></path>
    </svg>


    <% if user_signed_in? %>
      <% if current_user.admin? || current_user.director? || current_user.guest? %>
        <%= link_to t("slideshow.link1"), root_path, class: "link-nav text-h4" %>
        <%= link_to t("slideshow.link2"), audition_applications_path, class: "link-nav text-h4" %>
        <%= link_to t("slideshow.link3"), dashboard_index_path, class: "link-nav text-h4" %>
        <%= link_to t("slideshow.link4"), final_step_path, class: "link-nav text-h4" %>
        <%= link_to t("slideshow.link5"), invited_candidates_path, class: "link-nav text-h4" %>
        <%= link_to t("slideshow.link6"), dashboard_rapport_path, class: "link-nav text-h4" %>
      <% end %>
      <%= link_to t("sections.link3"), destroy_user_session_path, data: {turbo_method: :delete}, class: "link-nav text-h4" %>
      <%= link_to t("slideshow.link7"), help_path, class: "link-nav text-h4", style:"position:absolute;bottom:20px;left:20px" %>
    <% else %>
      <%= link_to t("sections.link1"), new_user_session_path, class: "link-nav text-h4" %>
      <%= link_to t("sections.link2"), new_user_registration_path, class:"link-nav text-h4" %>
      <%= link_to t("slideshow.link7"), help_path, class: "link-nav text-h4", style:"position:absolute;bottom:20px;left:20px" %>
    <% end %>
  </div>

  <div>
    <% if user_signed_in? && (current_user.director? || current_user.admin?) %>
      <%= link_to audition_applications_path(locale: I18n.locale), class: "navbar-brand" do %>
        <%= image_tag 'logo-audition.png', width:"200px" %>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'logo-audition.png', width:"200px" %>
      <% end %>
    <% end %>
  </div>
  <div class="nav-center" data-controller="lang">
    <b>
      <%= link_to "Fr", url_for(locale: 'fr', reset_password_token: params[:reset_password_token]), class: "link-nav", data: { lang_target: "link", locale: "fr" } %>
    </b>
    <b>
      <%= link_to "En", url_for(locale: 'en', reset_password_token: params[:reset_password_token]), class: "link-nav mr-5", data: { lang_target: "link", locale: "en" } %>
    </b>
  </div>
  <div class="menu-toggle burger" data-slideshow-target="burger">
    <button id="open-toggle-menu" aria-label="Toggle menu" class="menu-icon">
      <span class="line line1"></span>
      <span class="line line2"></span>
    </button>
  </div>
</div>