config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|fr/ do
    get 'dashboard/data', to: 'dashboard#data', as: :dashboard_data
    get 'dashboard/rapport', to: 'dashboard#rapport', as: :dashboard_rapport
    get "dashboard/download_rapport", to: "dashboard#download_rapport", as: :download_rapport
    get '/help', to: 'pages#help', as: :help
    get '/invited_candidates', to: 'pages#invited_candidates', as: :invited_candidates
    resources :dashboard, only: [:index, :show]
    devise_for :users
    root to: "pages#home"
    get "final_step", to: "pages#final_step", as: :final_step

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end

    resources :audition_applications do
      member do
        patch :update_status
        patch :update_ethnicity
        get :confirm_attendance
        post :confirm_attendance_message
        patch :update_attendance
      end
      collection do
        post :send_results
      end
      resources :votes, only: [:create]
    end
  end
end

app/views/pages/final_step.html.erb
<div class="main_container_final_step" data-controller="count-up-animation">
  <div class="container_central">
    <h1><%= t("final_step.h1") %></h1>
    <p><%= t("final_step.p1") %></p>
    <p><%= t("final_step.p2") %></p>
    <div class="mt-5">
      <p class="numbers"><%= t("final_step.tot_cand") %><br>
        <strong data-count-up-animation-target="number" data-target="<%= @applications.count %>">0</strong>
      </p>
      <div class="cards">
        <p class="numbers-flex"><%= t("final_step.rejected_cand") %><br>
          <strong data-count-up-animation-target="number" data-target="<%= @rejected_applications.count %>">0</strong>
        </p>

        <p class="numbers-flex"><%= t("final_step.accepted_cand") %><br>
          <strong data-count-up-animation-target="number" data-target="<%= @accepted_applications.count %>">0</strong>
        </p>

        <p class="numbers-flex"><%= t("final_step.pending_cand") %><br>
          <strong data-count-up-animation-target="number" data-target="<%= @pending_applications.count %>">0</strong>
        </p>
      </div>
    </div>
    <%= button_to t("final_step.notify_all_candidates"),
                  send_results_audition_applications_path,
                  method: :post,
                  data: { confirm: "Are you sure you want to notify all candidates now?", turbo_confirm: t("final_step.confirm_button") },
                  class: "submit-button mt-5"%>

    <div class="card-image">
      <img src="https://www.tanzimaugust.de/fileadmin/TiA/_processed_/f/3/csm_4_Ballet_de_l’Opéra_de_Lyon_Mycelium_c_Agathe_Poupeney_18f02ec2f6.jpg" alt="Audition Image">
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<div class="help-container my-3">
  <% case @user_type %>
    <% when :admin, :director, :guest %>
      <%= render "pages/help/admin"  %>
    <% when :candidate %>
      <%= render "pages/help/candidate" %>
    <% else %>
      <p class="text-center text-muted">No guide available for your role.</p>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="home-main-container">

  <div class="home-container-center">
    <% if user_signed_in? %>
      <% if current_user.role != "admin" && current_user.role != "director" && current_user.role != "guest" %>
        <div class="mt-5">
          <div class="body_p text-center">
            <% if current_user.audition_applications.present? %>
              <h3 class="text-h3">
                <%= t("home.welcome") %> <%= current_user.audition_applications.first.first_name %> <%= current_user.audition_applications.first.last_name %>
              </h3>

              <% application = current_user.audition_applications.first %>

              <% if application.status_published == nil || application.status_published == false %>
                <p class="text-p">
                  <%= t("home.status.pending") %>
                </p>
              <% elsif application.status_published == true && application.status == "accepted" && application.confirmed_attendance == true %>
                <p class="text-p">
                  <%= t("home.status.accepted.confirmed_attendance") %>
                </p>
              <% elsif application.status_published == true && application.status == "accepted" && application.confirmed_attendance == false %>
                <p class="text-p">
                  <%= t("home.status.accepted.unconfirmed_attendance") %>
                </p>
              <% elsif application.status == 'rejected' && application.status_published == true%>
                <p class="text-p">
                  <%= t("home.status.rejected") %>
                </p>
                <p class="text-p">
                  <%= t("home.questions") %>
                </p>
              <% end %>
            <% else %>
              <p class="text-p">
                <%= t("home.good_luck").html_safe %>
              </p>
            <% end %>
          </div>
          <div class="d-flex justify-content-center" style="margin-top: 20px; width: 100%">
            <%= image_tag "https://www.dancereflections-vancleefarpels.com/sites/default/files/styles/original_webp/public/2023-05/logo-opera-de-lyon.png?itok=FrOFCxxA",style:"width:25%" %>
          </div>
          <div class="text-center mt-5">
            <% if current_user.audition_applications.present? %>
              <% if current_user.audition_applications.first.status == 'accepted' && current_user.audition_applications.first.status_published == true %>
                <% if current_user.audition_applications.first.confirmed_attendance == false %>
                  <%= link_to confirm_attendance_audition_application_path(current_user.audition_applications.first), method: :get, class: "button" do %>
                    <span><%= t("home.btn.confirm_attendance") %></span>
                  <% end %>
                <% end %>
                <%= link_to audition_application_path(current_user.audition_applications.first), class:"button" do%>
                  <span><%= t("home.btn.application_check") %></span>
                <% end %>
              <% else %>
                <%= link_to audition_application_path(current_user.audition_applications.first), class:"button" do%>
                  <span><%= t("home.btn.application_check") %></span>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to new_audition_application_path, class:"button" do %>
                <span><%= t("home.btn.apply_audition") %></span>
              <% end %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="mt-5">
          <div class="text-center mt-3 rounded-top-logedIn">
            <img class="" src="https://www.dansesaveclaplume.com/wordpress/wp-content/gallery/soiree-jiri-kylian-ballet-de-lopera-de-lyon/b-bella-figura_1.jpg" alt="Ballet de l'Opera de Lyon Studio">
          </div>
          <div class="text-center mt-5">
            <div class="d-flex justify-content-center" style=" width: 50%; margin: 10px auto">
              <%= image_tag "https://www.dancereflections-vancleefarpels.com/sites/default/files/styles/original_webp/public/2023-05/logo-opera-de-lyon.png?itok=FrOFCxxA", class:"logo-home" %>
            </div>
            <%= link_to audition_applications_path, class:"button mt-3" do %>
              <span><%= t("home.btn.applications") %></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <%else%>
      <div class="rounded-top">
        <img class="img-home" src="https://api.opera-lyon.com/assets/q80-w960/bfda6276/bloc_tournees_ballet.jpg">
      </div>
      <div class="title-holder">
        <h1 class="text-h2"><%= t("home.main_title") %></h1>
          <p class="body_p">Saison 2025 - 2026</p>
          <p>
            <%= link_to new_user_registration_path, class: "button" do %>
              <span><%= t("sections.link2") %></span>
            <% end %>
            <%= link_to new_user_session_path, class:"button" do %>
              <span><%= t("sections.link1") %></span>
            <% end %>
          </p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/invited_candidates.erb
<div class="container mt-3">
  <h1 class="text-center"><%= t('invited_candidates.h1') %></h1>
  <%= form_with url: invited_candidates_path, method: :get, local: true, data: { turbo_frame: "invited_list" }, class: "filter-form mb-3" do %>
  <div class="filter-show">
    <div class="filter-field">
      <%= label_tag :confirmed_attendance, t('invited_candidates.filter_by_attendance') %>
      <%= select_tag :confirmed_attendance,
            options_for_select([
              ["All", ""],
              ["Confirmed", "true"],
              ["Not Confirmed", "false"]
            ], params[:confirmed_attendance]),
            class: "form-control",
            onchange: "this.form.requestSubmit();" %>
    </div>
  </div>
  <% end %>
  <!-- Applications List -->
  <turbo-frame id="invited_list">
    <div class="text-center">
        <p> <%= @audition_applications.count %>/<%= AuditionApplication.where(status:'accepted', status_published:true).count %></p>
    </div>
    <section class="tiles-index my-4">
      <% @audition_applications.each do |application| %>
        <article class="style1 tile <%= 'confirmed' if application.status_published && application.confirmed_attendance %> <%= 'not-confirmed' if application.status_published && !application.confirmed_attendance %>">
          <span class="image">
            <% if application.profile_image.present? %>
              <%= image_tag(application.profile_image) %>
            <% else %>
              <%= cl_image_tag application.photo.key %>
            <% end %>
          </span>

          <a href="<%= audition_application_path(application) %>" target="_top">
            <h3 id="text-tiles"><%= application.first_name %> <%= application.last_name %></h3>
            <br>
            <h5><%= application.nationality %></h5>
            <div class="content">
              <h5><%= application.height %>m</h5>
            </div>
          </a>

          <% unless application.status != 'pending' %>
            <% if current_user.admin? || current_user.director? %>
              <div class="votes">
                <% ['yes', 'maybe', 'no'].each do |vote| %>
                  <%= form_with url: audition_application_votes_path(application), method: :post do %>
                    <%= hidden_field_tag :value, vote %>
                    <%= submit_tag "", class: "btn-vote btn-#{vote}", title: vote.capitalize %>
                  <% end %>
                <% end %>

                <% if current_user.director? %>
                  <%= form_with url: audition_application_votes_path(application), method: :post do %>
                    <%= hidden_field_tag :value, 'star' %>
                    <%= submit_tag "", class: "btn-vote btn-star", title: "Star" %>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </article>
      <% end %>
    </section>
  </turbo-frame>
</div>